version: '2'
services:

  # The Application
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file: '.env'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"

  # The Web Server
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - "${LE_DIR}:/etc/letsencrypt"
      - ./public:/var/www/public
    ports:
      - 80:80
      - 443:443

  # The Database
  database:
    image: bitnami/mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    ports:
      - "33061:3306"

#  # redis
#  cache:
#    image: redis:3.0-alpine

volumes:
  dbdata: